openapi: 3.0.1
info:
  title: Pipedrive API v1 Activities LegacyTeams API
  version: 1.0.0
  description: 'Activities are appointments/tasks/events on a calendar that can be associated with a deal, a lead, a person and an organization. Activities can be of different type (such as call, meeting, lunch or a custom type - see ActivityTypes object) and can be assigned to a particular user. Note that activities can also be created without a specific date/time.

    '
servers:
- url: https://api.pipedrive.com/v1
tags:
- name: LegacyTeams
  description: 'Legacy teams allow you to form groups of users withing the organization for more efficient management. Previously Legacy Teams were called Teams and occupied the `v1/teams*` path. They''re being deprecated because we are preparing for an upgraded version of the Teams API, which requires migrating the current functionality to a new path URL `v1/legacyTeams*`. The functionality and [OAuth scopes](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations) of all the Teams API endpoints will remain the same.

    '
paths:
  /legacyTeams:
    get:
      summary: Get all teams
      description: Returns data about teams within the company.
      x-token-cost: 20
      operationId: getTeams
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - users:read
      parameters:
      - in: query
        name: order_by
        schema:
          type: string
          enum:
          - id
          - name
          - manager_id
          - active_flag
          default: id
        description: The field name to sort returned teams by
      - in: query
        name: skip_users
        schema:
          title: numberBooleanDefault0
          type: number
          default: 0
          enum:
          - 0
          - 1
        description: When enabled, the teams will not include IDs of member users
      responses:
        '200':
          description: The list of team objects
          content:
            application/json:
              schema:
                title: GetTeamsResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        title: baseTeam
                        allOf:
                        - title: teamId
                          type: object
                          properties:
                            id:
                              type: integer
                              description: The team ID
                        - type: object
                          title: updateTeamWithAdditionalProperties
                          allOf:
                          - title: updateTeamRequest
                            allOf:
                            - title: addTeamRequest
                              type: object
                              properties:
                                name:
                                  type: string
                                  description: The team name
                                description:
                                  type: string
                                  description: The team description
                                manager_id:
                                  type: integer
                                  description: The team manager ID
                                users:
                                  type: array
                                  items:
                                    type: integer
                                  description: The list of user IDs
                            - type: object
                              properties:
                                active_flag:
                                  allOf:
                                  - title: numberBoolean
                                    type: number
                                    enum:
                                    - 0
                                    - 1
                                  description: Flag that indicates whether the team is active
                                deleted_flag:
                                  allOf:
                                  - title: numberBoolean
                                    type: number
                                    enum:
                                    - 0
                                    - 1
                                  description: Flag that indicates whether the team is deleted
                          - type: object
                            title: baseTeamAdditionalProperties
                            properties:
                              add_time:
                                type: string
                                description: 'The team creation time. Format: YYYY-MM-DD HH:MM:SS'
                              created_by_user_id:
                                type: integer
                                description: The ID of the user who created the team
              example:
                success: true
                data:
                - id: 1
                  name: Closers
                  description: Berlin office Sales Team
                  manager_id: 4
                  users:
                  - 2
                  - 3
                  - 4
                  - 5
                  active_flag: 1
                  deleted_flag: 0
                  add_time: '2019-10-07 09:06:09'
                  created_by_user_id: 2
                - id: 2
                  name: Coffee
                  description: London office Sales Team
                  manager_id: 7
                  users:
                  - 5
                  - 8
                  active_flag: 0
                  deleted_flag: 0
                  add_time: '2018-04-11 12:54:43'
                  created_by_user_id: 7
    post:
      summary: Add a new team
      description: Adds a new team to the company and returns the created object.
      x-token-cost: 10
      operationId: addTeam
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - admin
      requestBody:
        content:
          application/json:
            schema:
              title: addTeamRequest
              type: object
              properties:
                name:
                  type: string
                  description: The team name
                description:
                  type: string
                  description: The team description
                manager_id:
                  type: integer
                  description: The team manager ID
                users:
                  type: array
                  items:
                    type: integer
                  description: The list of user IDs
              required:
              - name
              - manager_id
      responses:
        '200':
          description: The team data
          content:
            application/json:
              schema:
                title: GetTeamResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: baseTeam
                      allOf:
                      - title: teamId
                        type: object
                        properties:
                          id:
                            type: integer
                            description: The team ID
                      - type: object
                        title: updateTeamWithAdditionalProperties
                        allOf:
                        - title: updateTeamRequest
                          allOf:
                          - title: addTeamRequest
                            type: object
                            properties:
                              name:
                                type: string
                                description: The team name
                              description:
                                type: string
                                description: The team description
                              manager_id:
                                type: integer
                                description: The team manager ID
                              users:
                                type: array
                                items:
                                  type: integer
                                description: The list of user IDs
                          - type: object
                            properties:
                              active_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is active
                              deleted_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is deleted
                        - type: object
                          title: baseTeamAdditionalProperties
                          properties:
                            add_time:
                              type: string
                              description: 'The team creation time. Format: YYYY-MM-DD HH:MM:SS'
                            created_by_user_id:
                              type: integer
                              description: The ID of the user who created the team
              example:
                success: true
                data:
                  id: 1
                  name: Closers
                  description: Berlin office Sales Team
                  manager_id: 4
                  users:
                  - 2
                  - 3
                  - 5
                  active_flag: 1
                  deleted_flag: 0
                  add_time: '2019-10-07 09:06:09'
                  created_by_user_id: 2
        '403':
          description: Forbidden response
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: You do not have permissions to do this.
                error_info: Please check developers.pipedrive.com
                data: null
                additional_data: null
  /legacyTeams/{id}:
    get:
      summary: Get a single team
      description: Returns data about a specific team.
      x-token-cost: 2
      operationId: getTeam
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - users:read
      parameters:
      - in: path
        name: id
        description: The ID of the team
        required: true
        schema:
          type: integer
      - in: query
        name: skip_users
        schema:
          title: numberBooleanDefault0
          type: number
          default: 0
          enum:
          - 0
          - 1
        description: When enabled, the teams will not include IDs of member users
      responses:
        '200':
          description: The team data
          content:
            application/json:
              schema:
                title: GetTeamResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: baseTeam
                      allOf:
                      - title: teamId
                        type: object
                        properties:
                          id:
                            type: integer
                            description: The team ID
                      - type: object
                        title: updateTeamWithAdditionalProperties
                        allOf:
                        - title: updateTeamRequest
                          allOf:
                          - title: addTeamRequest
                            type: object
                            properties:
                              name:
                                type: string
                                description: The team name
                              description:
                                type: string
                                description: The team description
                              manager_id:
                                type: integer
                                description: The team manager ID
                              users:
                                type: array
                                items:
                                  type: integer
                                description: The list of user IDs
                          - type: object
                            properties:
                              active_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is active
                              deleted_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is deleted
                        - type: object
                          title: baseTeamAdditionalProperties
                          properties:
                            add_time:
                              type: string
                              description: 'The team creation time. Format: YYYY-MM-DD HH:MM:SS'
                            created_by_user_id:
                              type: integer
                              description: The ID of the user who created the team
              example:
                success: true
                data:
                  id: 1
                  name: Closers
                  description: Berlin office Sales Team
                  manager_id: 4
                  users:
                  - 2
                  - 3
                  - 5
                  active_flag: 1
                  deleted_flag: 0
                  add_time: '2019-10-07 09:06:09'
                  created_by_user_id: 2
        '404':
          description: Team with specified ID does not exist or is inaccessible
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: Team 1 does not exist
    put:
      summary: Update a team
      description: Updates an existing team and returns the updated object.
      x-token-cost: 10
      operationId: updateTeam
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - admin
      parameters:
      - in: path
        name: id
        description: The ID of the team
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              title: updateTeamRequest
              allOf:
              - title: addTeamRequest
                type: object
                properties:
                  name:
                    type: string
                    description: The team name
                  description:
                    type: string
                    description: The team description
                  manager_id:
                    type: integer
                    description: The team manager ID
                  users:
                    type: array
                    items:
                      type: integer
                    description: The list of user IDs
              - type: object
                properties:
                  active_flag:
                    allOf:
                    - title: numberBoolean
                      type: number
                      enum:
                      - 0
                      - 1
                    description: Flag that indicates whether the team is active
                  deleted_flag:
                    allOf:
                    - title: numberBoolean
                      type: number
                      enum:
                      - 0
                      - 1
                    description: Flag that indicates whether the team is deleted
      responses:
        '200':
          description: The team data
          content:
            application/json:
              schema:
                title: GetTeamResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: baseTeam
                      allOf:
                      - title: teamId
                        type: object
                        properties:
                          id:
                            type: integer
                            description: The team ID
                      - type: object
                        title: updateTeamWithAdditionalProperties
                        allOf:
                        - title: updateTeamRequest
                          allOf:
                          - title: addTeamRequest
                            type: object
                            properties:
                              name:
                                type: string
                                description: The team name
                              description:
                                type: string
                                description: The team description
                              manager_id:
                                type: integer
                                description: The team manager ID
                              users:
                                type: array
                                items:
                                  type: integer
                                description: The list of user IDs
                          - type: object
                            properties:
                              active_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is active
                              deleted_flag:
                                allOf:
                                - title: numberBoolean
                                  type: number
                                  enum:
                                  - 0
                                  - 1
                                description: Flag that indicates whether the team is deleted
                        - type: object
                          title: baseTeamAdditionalProperties
                          properties:
                            add_time:
                              type: string
                              description: 'The team creation time. Format: YYYY-MM-DD HH:MM:SS'
                            created_by_user_id:
                              type: integer
                              description: The ID of the user who created the team
              example:
                success: true
                data:
                  id: 1
                  name: Closers
                  description: Berlin office Sales Team
                  manager_id: 4
                  users:
                  - 2
                  - 3
                  - 5
                  active_flag: 1
                  deleted_flag: 0
                  add_time: '2019-10-07 09:06:09'
                  created_by_user_id: 2
        '403':
          description: Forbidden response
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: You do not have permissions to do this.
                error_info: Please check developers.pipedrive.com
                data: null
                additional_data: null
        '404':
          description: Team with specified ID does not exist or is inaccessible
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: Team 1 does not exist
  /legacyTeams/{id}/users:
    get:
      summary: Get all users in a team
      description: Returns a list of all user IDs within a team.
      x-token-cost: 20
      operationId: getTeamUsers
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - users:read
      parameters:
      - in: path
        name: id
        description: The ID of the team
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A list of user IDs within a team
          content:
            application/json:
              schema:
                title: userIds
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: integer
                      description: The list of user IDs
              example:
                success: true
                data:
                - 2
                - 3
                - 4
                - 5
        '404':
          description: Team with specified ID does not exist or is inaccessible
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: Team 1 does not exist
    post:
      summary: Add users to a team
      description: Adds users to an existing team.
      x-token-cost: 10
      operationId: addTeamUser
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - admin
      parameters:
      - in: path
        name: id
        description: The ID of the team
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              title: addTeamUserRequest
              type: object
              required:
              - users
              properties:
                users:
                  type: array
                  items:
                    type: integer
                  description: The list of user IDs
      responses:
        '200':
          description: A list of user IDs within a team
          content:
            application/json:
              schema:
                title: userIds
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: integer
                      description: The list of user IDs
              example:
                success: true
                data:
                - 2
                - 3
                - 4
                - 5
        '403':
          description: Forbidden response
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: You do not have permissions to do this.
                error_info: Please check developers.pipedrive.com
                data: null
                additional_data: null
        '404':
          description: Team with specified ID does not exist or is inaccessible
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: Team 1 does not exist
    delete:
      summary: Delete users from a team
      description: Deletes users from an existing team.
      x-token-cost: 10
      operationId: deleteTeamUser
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - admin
      parameters:
      - in: path
        name: id
        description: The ID of the team
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              title: deleteTeamUserRequest
              type: object
              required:
              - users
              properties:
                users:
                  type: array
                  items:
                    type: integer
                  description: The list of user IDs
      responses:
        '200':
          description: A list of user IDs within a team
          content:
            application/json:
              schema:
                title: userIds
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: integer
                      description: The list of user IDs
              example:
                success: true
                data:
                - 2
                - 3
                - 4
                - 5
        '403':
          description: Forbidden response
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: You do not have permissions to do this.
                error_info: Please check developers.pipedrive.com
                data: null
                additional_data: null
        '404':
          description: Team with specified ID does not exist or is inaccessible
          content:
            application/json:
              schema:
                title: failResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  error:
                    type: string
                    description: The error message
              example:
                success: false
                error: Team 1 does not exist
  /legacyTeams/user/{id}:
    get:
      summary: Get all teams of a user
      description: Returns data about all teams which have the specified user as a member.
      x-token-cost: 20
      operationId: getUserTeams
      deprecated: true
      tags:
      - LegacyTeams
      security:
      - api_key: []
      - oauth2:
        - users:read
      parameters:
      - in: path
        name: id
        description: The ID of the user
        required: true
        schema:
          type: integer
      - in: query
        name: order_by
        schema:
          type: string
          enum:
          - id
          - name
          - manager_id
          - active_flag
          default: id
        description: The field name to sort returned teams by
      - in: query
        name: skip_users
        schema:
          title: numberBooleanDefault0
          type: number
          default: 0
          enum:
          - 0
          - 1
        description: When enabled, the teams will not include IDs of member users
      responses:
        '200':
          description: The list of team objects
          content:
            application/json:
              schema:
                title: GetTeamsResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        title: baseTeam
                        allOf:
                        - title: teamId
                          type: object
                          properties:
                            id:
                              type: integer
                              description: The team ID
                        - type: object
                          title: updateTeamWithAdditionalProperties
                          allOf:
                          - title: updateTeamRequest
                            allOf:
                            - title: addTeamRequest
                              type: object
                              properties:
                                name:
                                  type: string
                                  description: The team name
                                description:
                                  type: string
                                  description: The team description
                                manager_id:
                                  type: integer
                                  description: The team manager ID
                                users:
                                  type: array
                                  items:
                                    type: integer
                                  description: The list of user IDs
                            - type: object
                              properties:
                                active_flag:
                                  allOf:
                                  - title: numberBoolean
                                    type: number
                                    enum:
                                    - 0
                                    - 1
                                  description: Flag that indicates whether the team is active
                                deleted_flag:
                                  allOf:
                                  - title: numberBoolean
                                    type: number
                                    enum:
                                    - 0
                                    - 1
                                  description: Flag that indicates whether the team is deleted
                          - type: object
                            title: baseTeamAdditionalProperties
                            properties:
                              add_time:
                                type: string
                                description: 'The team creation time. Format: YYYY-MM-DD HH:MM:SS'
                              created_by_user_id:
                                type: integer
                                description: The ID of the user who created the team
              example:
                success: true
                data:
                - id: 1
                  name: Closers
                  description: Berlin office Sales Team
                  manager_id: 4
                  users:
                  - 2
                  - 3
                  - 4
                  - 5
                  active_flag: 1
                  deleted_flag: 0
                  add_time: '2019-10-07 09:06:09'
                  created_by_user_id: 2
                - id: 2
                  name: Coffee
                  description: London office Sales Team
                  manager_id: 7
                  users:
                  - 5
                  - 8
                  active_flag: 0
                  deleted_flag: 0
                  add_time: '2018-04-11 12:54:43'
                  created_by_user_id: 7
components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic
      description: Base 64 encoded string containing the `client_id` and `client_secret` values. The header value should be `Basic <base64(client_id:client_secret)>`.
    api_key:
      type: apiKey
      name: x-api-token
      in: header
    oauth2:
      type: oauth2
      description: For more information, see https://pipedrive.readme.io/docs/marketplace-oauth-authorization
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.pipedrive.com/oauth/authorize
          tokenUrl: https://oauth.pipedrive.com/oauth/token
          refreshUrl: https://oauth.pipedrive.com/oauth/token
          scopes:
            base: Read settings of the authorized user and currencies in an account
            deals:read: Read most of the data about deals and related entities - deal fields, products, followers, participants; all notes, files, filters, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            deals:full: Create, read, update and delete deals, its participants and followers; all files, notes, and filters. It also includes read access to deal fields, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            mail:read: Read mail threads and messages
            mail:full: Read, update and delete mail threads. Also grants read access to mail messages
            activities:read: Read activities, its fields and types; all files and filters
            activities:full: Create, read, update and delete activities and all files and filters. Also includes read access to activity fields and types
            contacts:read: Read the data about persons and organizations, their related fields and followers; also all notes, files, filters
            contacts:full: Create, read, update and delete persons and organizations and their followers; all notes, files, filters. Also grants read access to contacts-related fields
            products:read: Read products, its fields, files, followers and products connected to a deal
            products:full: Create, read, update and delete products and its fields; add products to deals
            deal-fields:full: Create, read, update and delete deal fields
            product-fields:full: Create, read, update and delete product fields
            contact-fields:full: Create, read, update and delete person and organization fields
            projects:read: Read projects and its fields, tasks and project templates
            projects:full: Create, read, update and delete projects and its fields; add projects templates and project related tasks
            users:read: Read data about users (people with access to a Pipedrive account), their permissions, roles and followers
            recents:read: Read all recent changes occurred in an account. Includes data about activities, activity types, deals, files, filters, notes, persons, organizations, pipelines, stages, products and users
            search:read: Search across the account for deals, persons, organizations, files and products, and see details about the returned results
            admin: Allows to do many things that an administrator can do in a Pipedrive company account - create, read, update and delete pipelines and its stages; deal, person and organization fields; activity types; users and permissions, etc. It also allows the app to create webhooks and fetch and delete webhooks that are created by the app
            leads:read: Read data about leads and lead labels
            leads:full: Create, read, update and delete leads and lead labels
            phone-integration: Enables advanced call integration features like logging call duration and other metadata, and play call recordings inside Pipedrive
            goals:read: Read data on all goals
            goals:full: Create, read, update and delete goals
            video-calls: Allows application to register as a video call integration provider and create conference links
            messengers-integration: Allows application to register as a messengers integration provider and allows them to deliver incoming messages and their statuses
