openapi: 3.0.1
info:
  title: Pipedrive API v1 Activities ActivityTypes API
  version: 1.0.0
  description: 'Activities are appointments/tasks/events on a calendar that can be associated with a deal, a lead, a person and an organization. Activities can be of different type (such as call, meeting, lunch or a custom type - see ActivityTypes object) and can be assigned to a particular user. Note that activities can also be created without a specific date/time.

    '
servers:
- url: https://api.pipedrive.com/v1
tags:
- name: ActivityTypes
  description: 'Activity types represent different kinds of activities that can be stored. Each activity type is presented to the user with an icon and a name. Additionally, a color can be defined (not implemented in the Pipedrive app as of today). Activity types are linked to activities via `ActivityType.key_string = Activity.type`. The `key_string` will be generated by the API based on the given name of the activity type upon creation, and cannot be changed. Activity types should be presented to the user in an ordered manner, using the `ActivityType.order_nr` value.

    '
paths:
  /activityTypes:
    get:
      summary: Get all activity types
      description: Returns all activity types.
      x-token-cost: 20
      operationId: getActivityTypes
      tags:
      - ActivityTypes
      security:
      - api_key: []
      - oauth2:
        - activities:read
        - activities:full
        - admin
      responses:
        '200':
          description: A list of activity types
          content:
            application/json:
              schema:
                title: GetActivityTypesResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        title: ActivityType
                        properties:
                          id:
                            type: integer
                            description: The ID of the activity type
                          name:
                            type: string
                            description: The name of the activity type
                          icon_key:
                            type: string
                            description: Icon graphic to use for representing this activity type
                            enum:
                            - task
                            - email
                            - meeting
                            - deadline
                            - call
                            - lunch
                            - calendar
                            - downarrow
                            - document
                            - smartphone
                            - camera
                            - scissors
                            - cogs
                            - bubble
                            - uparrow
                            - checkbox
                            - signpost
                            - shuffle
                            - addressbook
                            - linegraph
                            - picture
                            - car
                            - world
                            - search
                            - clip
                            - sound
                            - brush
                            - key
                            - padlock
                            - pricetag
                            - suitcase
                            - finish
                            - plane
                            - loop
                            - wifi
                            - truck
                            - cart
                            - bulb
                            - bell
                            - presentation
                          color:
                            type: string
                            description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
                          order_nr:
                            type: integer
                            description: An order number for the activity type. Order numbers should be used to order the types in the activity type selections.
                          key_string:
                            type: string
                            description: A string that is generated by the API based on the given name of the activity type upon creation
                          active_flag:
                            type: boolean
                            description: The active flag of the activity type
                          is_custom_flag:
                            type: boolean
                            description: Whether the activity type is a custom one or not
                          add_time:
                            type: string
                            format: date-time
                            description: The creation time of the activity type
                          update_time:
                            type: string
                            format: date-time
                            description: The update time of the activity type
                      description: The array of activity types
              example:
                success: true
                data:
                - id: 4
                  order_nr: 1
                  name: Deadline
                  key_string: deadline
                  icon_key: deadline
                  active_flag: true
                  color: FFFFFF
                  is_custom_flag: false
                  add_time: '2019-10-04 16:24:55'
                  update_time: '2020-03-11 13:53:01'
                - id: 5
                  order_nr: 2
                  name: Call
                  key_string: call
                  icon_key: call
                  active_flag: true
                  color: FFFFFF
                  is_custom_flag: false
                  add_time: '2019-12-21 19:44:01'
                  update_time: '2019-12-21 19:44:01'
    post:
      summary: Add new activity type
      description: Adds a new activity type.
      x-token-cost: 10
      operationId: addActivityType
      tags:
      - ActivityTypes
      security:
      - api_key: []
      - oauth2:
        - admin
      requestBody:
        content:
          application/json:
            schema:
              title: addActivityTypeRequest
              type: object
              required:
              - name
              - icon_key
              properties:
                name:
                  type: string
                  example: call
                  description: The name of the activity type
                icon_key:
                  type: string
                  description: Icon graphic to use for representing this activity type
                  enum:
                  - task
                  - email
                  - meeting
                  - deadline
                  - call
                  - lunch
                  - calendar
                  - downarrow
                  - document
                  - smartphone
                  - camera
                  - scissors
                  - cogs
                  - bubble
                  - uparrow
                  - checkbox
                  - signpost
                  - shuffle
                  - addressbook
                  - linegraph
                  - picture
                  - car
                  - world
                  - search
                  - clip
                  - sound
                  - brush
                  - key
                  - padlock
                  - pricetag
                  - suitcase
                  - finish
                  - plane
                  - loop
                  - wifi
                  - truck
                  - cart
                  - bulb
                  - bell
                  - presentation
                color:
                  type: string
                  example: FFFFFF
                  description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
      responses:
        '200':
          description: The activity type was successfully created
          content:
            application/json:
              schema:
                title: UpsertActivityTypeResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: ActivityType
                      properties:
                        id:
                          type: integer
                          description: The ID of the activity type
                        name:
                          type: string
                          description: The name of the activity type
                        icon_key:
                          type: string
                          description: Icon graphic to use for representing this activity type
                          enum:
                          - task
                          - email
                          - meeting
                          - deadline
                          - call
                          - lunch
                          - calendar
                          - downarrow
                          - document
                          - smartphone
                          - camera
                          - scissors
                          - cogs
                          - bubble
                          - uparrow
                          - checkbox
                          - signpost
                          - shuffle
                          - addressbook
                          - linegraph
                          - picture
                          - car
                          - world
                          - search
                          - clip
                          - sound
                          - brush
                          - key
                          - padlock
                          - pricetag
                          - suitcase
                          - finish
                          - plane
                          - loop
                          - wifi
                          - truck
                          - cart
                          - bulb
                          - bell
                          - presentation
                        color:
                          type: string
                          description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
                        order_nr:
                          type: integer
                          description: An order number for the activity type. Order numbers should be used to order the types in the activity type selections.
                        key_string:
                          type: string
                          description: A string that is generated by the API based on the given name of the activity type upon creation
                        active_flag:
                          type: boolean
                          description: The active flag of the activity type
                        is_custom_flag:
                          type: boolean
                          description: Whether the activity type is a custom one or not
                        add_time:
                          type: string
                          format: date-time
                          description: The creation time of the activity type
                        update_time:
                          type: string
                          format: date-time
                          description: The update time of the activity type
              example:
                success: true
                data:
                  id: 12
                  order_nr: 1
                  name: Video call
                  key_string: video_call
                  icon_key: camera
                  active_flag: true
                  color: aeb31b
                  is_custom_flag: true
                  add_time: '2020-09-01 10:16:23'
                  update_time: '2020-09-01 10:16:23'
  /activityTypes/{id}:
    delete:
      summary: Delete an activity type
      description: Marks an activity type as deleted.
      x-token-cost: 6
      operationId: deleteActivityType
      tags:
      - ActivityTypes
      security:
      - api_key: []
      - oauth2:
        - admin
      parameters:
      - in: path
        name: id
        description: The ID of the activity type
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: The activity type was successfully deleted
          content:
            application/json:
              schema:
                title: UpsertActivityTypeResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: ActivityType
                      properties:
                        id:
                          type: integer
                          description: The ID of the activity type
                        name:
                          type: string
                          description: The name of the activity type
                        icon_key:
                          type: string
                          description: Icon graphic to use for representing this activity type
                          enum:
                          - task
                          - email
                          - meeting
                          - deadline
                          - call
                          - lunch
                          - calendar
                          - downarrow
                          - document
                          - smartphone
                          - camera
                          - scissors
                          - cogs
                          - bubble
                          - uparrow
                          - checkbox
                          - signpost
                          - shuffle
                          - addressbook
                          - linegraph
                          - picture
                          - car
                          - world
                          - search
                          - clip
                          - sound
                          - brush
                          - key
                          - padlock
                          - pricetag
                          - suitcase
                          - finish
                          - plane
                          - loop
                          - wifi
                          - truck
                          - cart
                          - bulb
                          - bell
                          - presentation
                        color:
                          type: string
                          description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
                        order_nr:
                          type: integer
                          description: An order number for the activity type. Order numbers should be used to order the types in the activity type selections.
                        key_string:
                          type: string
                          description: A string that is generated by the API based on the given name of the activity type upon creation
                        active_flag:
                          type: boolean
                          description: The active flag of the activity type
                        is_custom_flag:
                          type: boolean
                          description: Whether the activity type is a custom one or not
                        add_time:
                          type: string
                          format: date-time
                          description: The creation time of the activity type
                        update_time:
                          type: string
                          format: date-time
                          description: The update time of the activity type
              example:
                success: true
                data:
                  id: 12
                  order_nr: 1
                  name: Video call
                  key_string: video_call
                  icon_key: camera
                  active_flag: false
                  color: aeb31b
                  is_custom_flag: true
                  add_time: '2020-09-01 10:16:23'
                  update_time: '2020-09-01 19:59:59'
    put:
      summary: Update an activity type
      description: Updates an activity type.
      x-token-cost: 10
      operationId: updateActivityType
      tags:
      - ActivityTypes
      security:
      - api_key: []
      - oauth2:
        - admin
      parameters:
      - in: path
        name: id
        description: The ID of the activity type
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              title: updateActivityTypeRequest
              type: object
              properties:
                name:
                  type: string
                  description: The name of the activity type
                icon_key:
                  type: string
                  description: Icon graphic to use for representing this activity type
                  enum:
                  - task
                  - email
                  - meeting
                  - deadline
                  - call
                  - lunch
                  - calendar
                  - downarrow
                  - document
                  - smartphone
                  - camera
                  - scissors
                  - cogs
                  - bubble
                  - uparrow
                  - checkbox
                  - signpost
                  - shuffle
                  - addressbook
                  - linegraph
                  - picture
                  - car
                  - world
                  - search
                  - clip
                  - sound
                  - brush
                  - key
                  - padlock
                  - pricetag
                  - suitcase
                  - finish
                  - plane
                  - loop
                  - wifi
                  - truck
                  - cart
                  - bulb
                  - bell
                  - presentation
                color:
                  type: string
                  description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
                order_nr:
                  type: integer
                  description: An order number for this activity type. Order numbers should be used to order the types in the activity type selections.
      responses:
        '200':
          description: The activity type was successfully updated
          content:
            application/json:
              schema:
                title: UpsertActivityTypeResponse
                allOf:
                - title: baseResponse
                  type: object
                  properties:
                    success:
                      type: boolean
                      description: If the response is successful or not
                - type: object
                  properties:
                    data:
                      type: object
                      title: ActivityType
                      properties:
                        id:
                          type: integer
                          description: The ID of the activity type
                        name:
                          type: string
                          description: The name of the activity type
                        icon_key:
                          type: string
                          description: Icon graphic to use for representing this activity type
                          enum:
                          - task
                          - email
                          - meeting
                          - deadline
                          - call
                          - lunch
                          - calendar
                          - downarrow
                          - document
                          - smartphone
                          - camera
                          - scissors
                          - cogs
                          - bubble
                          - uparrow
                          - checkbox
                          - signpost
                          - shuffle
                          - addressbook
                          - linegraph
                          - picture
                          - car
                          - world
                          - search
                          - clip
                          - sound
                          - brush
                          - key
                          - padlock
                          - pricetag
                          - suitcase
                          - finish
                          - plane
                          - loop
                          - wifi
                          - truck
                          - cart
                          - bulb
                          - bell
                          - presentation
                        color:
                          type: string
                          description: A designated color for the activity type in 6-character HEX format (e.g. `FFFFFF` for white, `000000` for black)
                        order_nr:
                          type: integer
                          description: An order number for the activity type. Order numbers should be used to order the types in the activity type selections.
                        key_string:
                          type: string
                          description: A string that is generated by the API based on the given name of the activity type upon creation
                        active_flag:
                          type: boolean
                          description: The active flag of the activity type
                        is_custom_flag:
                          type: boolean
                          description: Whether the activity type is a custom one or not
                        add_time:
                          type: string
                          format: date-time
                          description: The creation time of the activity type
                        update_time:
                          type: string
                          format: date-time
                          description: The update time of the activity type
              example:
                success: true
                data:
                  id: 12
                  order_nr: 1
                  name: Video call
                  key_string: video_call
                  icon_key: camera
                  active_flag: true
                  color: aeb31b
                  is_custom_flag: true
                  add_time: '2020-09-01 10:16:23'
                  update_time: '2020-09-01 14:12:09'
components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic
      description: Base 64 encoded string containing the `client_id` and `client_secret` values. The header value should be `Basic <base64(client_id:client_secret)>`.
    api_key:
      type: apiKey
      name: x-api-token
      in: header
    oauth2:
      type: oauth2
      description: For more information, see https://pipedrive.readme.io/docs/marketplace-oauth-authorization
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.pipedrive.com/oauth/authorize
          tokenUrl: https://oauth.pipedrive.com/oauth/token
          refreshUrl: https://oauth.pipedrive.com/oauth/token
          scopes:
            base: Read settings of the authorized user and currencies in an account
            deals:read: Read most of the data about deals and related entities - deal fields, products, followers, participants; all notes, files, filters, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            deals:full: Create, read, update and delete deals, its participants and followers; all files, notes, and filters. It also includes read access to deal fields, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            mail:read: Read mail threads and messages
            mail:full: Read, update and delete mail threads. Also grants read access to mail messages
            activities:read: Read activities, its fields and types; all files and filters
            activities:full: Create, read, update and delete activities and all files and filters. Also includes read access to activity fields and types
            contacts:read: Read the data about persons and organizations, their related fields and followers; also all notes, files, filters
            contacts:full: Create, read, update and delete persons and organizations and their followers; all notes, files, filters. Also grants read access to contacts-related fields
            products:read: Read products, its fields, files, followers and products connected to a deal
            products:full: Create, read, update and delete products and its fields; add products to deals
            deal-fields:full: Create, read, update and delete deal fields
            product-fields:full: Create, read, update and delete product fields
            contact-fields:full: Create, read, update and delete person and organization fields
            projects:read: Read projects and its fields, tasks and project templates
            projects:full: Create, read, update and delete projects and its fields; add projects templates and project related tasks
            users:read: Read data about users (people with access to a Pipedrive account), their permissions, roles and followers
            recents:read: Read all recent changes occurred in an account. Includes data about activities, activity types, deals, files, filters, notes, persons, organizations, pipelines, stages, products and users
            search:read: Search across the account for deals, persons, organizations, files and products, and see details about the returned results
            admin: Allows to do many things that an administrator can do in a Pipedrive company account - create, read, update and delete pipelines and its stages; deal, person and organization fields; activity types; users and permissions, etc. It also allows the app to create webhooks and fetch and delete webhooks that are created by the app
            leads:read: Read data about leads and lead labels
            leads:full: Create, read, update and delete leads and lead labels
            phone-integration: Enables advanced call integration features like logging call duration and other metadata, and play call recordings inside Pipedrive
            goals:read: Read data on all goals
            goals:full: Create, read, update and delete goals
            video-calls: Allows application to register as a video call integration provider and create conference links
            messengers-integration: Allows application to register as a messengers integration provider and allows them to deliver incoming messages and their statuses
