openapi: 3.0.1
info:
  title: Pipedrive API v1 Activities ProjectBoards API
  version: 1.0.0
  description: 'Activities are appointments/tasks/events on a calendar that can be associated with a deal, a lead, a person and an organization. Activities can be of different type (such as call, meeting, lunch or a custom type - see ActivityTypes object) and can be assigned to a particular user. Note that activities can also be created without a specific date/time.

    '
servers:
- url: https://api.pipedrive.com/v1
tags:
- name: ProjectBoards
  description: 'Project boards are used to organize projects into different phases. Each board contains phases that define the workflow for projects.

    '
paths:
  /projects/boards:
    get:
      summary: Get all project boards
      description: Returns all projects boards that are not deleted.
      x-token-cost: 20
      operationId: getProjectsBoards
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:read
        - projects:full
      responses:
        '200':
          description: A list of project board.
          content:
            application/json:
              schema:
                title: GetProjectBoardsResponse
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The ID of the project board
                        name:
                          description: Name of a project board
                          type: string
                        order_nr:
                          description: The order of a board
                          type: number
                        add_time:
                          type: string
                          description: 'The creation date and time of the board in UTC. Format: YYYY-MM-DD HH:MM:SS.'
                        update_time:
                          type: string
                          description: 'The update date and time of the board in UTC. Format: YYYY-MM-DD HH:MM:SS.'
                  additional_data:
                    type: object
                    nullable: true
                    example: null
              example:
                success: true
                data:
                - id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2023-09-12 11:12:18'
                  update_time: '2023-09-14 05:45:40'
                additional_data: null
  /projects/boards/{id}:
    get:
      summary: Get details of a board
      description: Returns the details of a specific project board.
      x-token-cost: 2
      operationId: getProjectsBoard
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:read
        - projects:full
      parameters:
      - in: path
        name: id
        description: The ID of the project board
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Get a project board.
          content:
            application/json:
              schema:
                title: GetProjectBoardResponse
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the project board
                      name:
                        description: Name of a project board
                        type: string
                      order_nr:
                        description: The order of a board
                        type: number
                      add_time:
                        type: string
                        description: 'The creation date and time of the board in UTC. Format: YYYY-MM-DD HH:MM:SS.'
                      update_time:
                        type: string
                        description: 'The update date and time of the board in UTC. Format: YYYY-MM-DD HH:MM:SS.'
                  additional_data:
                    type: object
                    nullable: true
                    example: null
              example:
                success: true
                data:
                  id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2023-09-12 11:12:18'
                  update_time: '2023-09-14 05:45:40'
                additional_data: null
  /boards:
    get:
      summary: Get all project boards
      description: Returns all active project boards.
      x-token-cost: 10
      operationId: getProjectsBoards
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:read
        - projects:full
      responses:
        '200':
          description: Get all project boards
          content:
            application/json:
              schema:
                title: GetProjectBoardsResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  data:
                    type: array
                    description: The array of project boards
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The ID of the project board
                        name:
                          type: string
                          description: The name of the project board
                        order_nr:
                          type: integer
                          description: The order of the board
                        add_time:
                          type: string
                          description: The creation date and time of the board in ISO 8601 format
                        update_time:
                          type: string
                          description: The update date and time of the board in ISO 8601 format
                  additional_data:
                    type: object
                    nullable: true
              example:
                success: true
                data:
                - id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2024-01-01T00:00:00.000Z'
                  update_time: '2024-01-01T00:00:00.000Z'
                additional_data: null
    post:
      summary: Add a project board
      description: Adds a new project board.
      x-token-cost: 5
      operationId: addProjectBoard
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:full
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: addProjectBoardRequest
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: The name of the project board
                order_nr:
                  type: integer
                  minimum: 1
                  description: The order of the board. Must be between 1 and the total number of boards + 1.
      responses:
        '200':
          description: Add a project board
          content:
            application/json:
              schema:
                title: UpsertProjectBoardResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the project board
                      name:
                        type: string
                        description: The name of the project board
                      order_nr:
                        type: integer
                        description: The order of the board
                      add_time:
                        type: string
                        description: The creation date and time of the board in ISO 8601 format
                      update_time:
                        type: string
                        description: The update date and time of the board in ISO 8601 format
              example:
                success: true
                data:
                  id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2024-01-01T00:00:00.000Z'
                  update_time: '2024-01-01T00:00:00.000Z'
  /boards/{id}:
    get:
      summary: Get details of a project board
      description: Returns the details of a specific project board.
      x-token-cost: 10
      operationId: getProjectsBoard
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:read
        - projects:full
      parameters:
      - in: path
        name: id
        description: The ID of the project board
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Get a project board
          content:
            application/json:
              schema:
                title: UpsertProjectBoardResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the project board
                      name:
                        type: string
                        description: The name of the project board
                      order_nr:
                        type: integer
                        description: The order of the board
                      add_time:
                        type: string
                        description: The creation date and time of the board in ISO 8601 format
                      update_time:
                        type: string
                        description: The update date and time of the board in ISO 8601 format
              example:
                success: true
                data:
                  id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2024-01-01T00:00:00.000Z'
                  update_time: '2024-01-01T00:00:00.000Z'
    patch:
      summary: Update a project board
      description: Updates the properties of a project board.
      x-token-cost: 5
      operationId: updateProjectBoard
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:full
      parameters:
      - in: path
        name: id
        description: The ID of the project board
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              title: updateProjectBoardRequest
              type: object
              properties:
                name:
                  type: string
                  description: The name of the project board
                order_nr:
                  type: integer
                  minimum: 1
                  description: The order of the board. Must be between 1 and the total number of boards + 1.
      responses:
        '200':
          description: Update a project board
          content:
            application/json:
              schema:
                title: UpsertProjectBoardResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the project board
                      name:
                        type: string
                        description: The name of the project board
                      order_nr:
                        type: integer
                        description: The order of the board
                      add_time:
                        type: string
                        description: The creation date and time of the board in ISO 8601 format
                      update_time:
                        type: string
                        description: The update date and time of the board in ISO 8601 format
              example:
                success: true
                data:
                  id: 1
                  name: Project Board
                  order_nr: 1
                  add_time: '2024-01-01T00:00:00.000Z'
                  update_time: '2024-01-01T00:00:00.000Z'
    delete:
      summary: Delete a project board
      description: Marks a project board as deleted.
      x-token-cost: 3
      operationId: deleteProjectBoard
      tags:
      - ProjectBoards
      security:
      - api_key: []
      - oauth2:
        - projects:full
      parameters:
      - in: path
        name: id
        description: The ID of the project board
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Delete a project board
          content:
            application/json:
              schema:
                title: DeleteProjectBoardResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the response is successful or not
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the deleted project board
              example:
                success: true
                data:
                  id: 1
components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic
      description: Base 64 encoded string containing the `client_id` and `client_secret` values. The header value should be `Basic <base64(client_id:client_secret)>`.
    api_key:
      type: apiKey
      name: x-api-token
      in: header
    oauth2:
      type: oauth2
      description: For more information, see https://pipedrive.readme.io/docs/marketplace-oauth-authorization
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.pipedrive.com/oauth/authorize
          tokenUrl: https://oauth.pipedrive.com/oauth/token
          refreshUrl: https://oauth.pipedrive.com/oauth/token
          scopes:
            base: Read settings of the authorized user and currencies in an account
            deals:read: Read most of the data about deals and related entities - deal fields, products, followers, participants; all notes, files, filters, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            deals:full: Create, read, update and delete deals, its participants and followers; all files, notes, and filters. It also includes read access to deal fields, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            mail:read: Read mail threads and messages
            mail:full: Read, update and delete mail threads. Also grants read access to mail messages
            activities:read: Read activities, its fields and types; all files and filters
            activities:full: Create, read, update and delete activities and all files and filters. Also includes read access to activity fields and types
            contacts:read: Read the data about persons and organizations, their related fields and followers; also all notes, files, filters
            contacts:full: Create, read, update and delete persons and organizations and their followers; all notes, files, filters. Also grants read access to contacts-related fields
            products:read: Read products, its fields, files, followers and products connected to a deal
            products:full: Create, read, update and delete products and its fields; add products to deals
            deal-fields:full: Create, read, update and delete deal fields
            product-fields:full: Create, read, update and delete product fields
            contact-fields:full: Create, read, update and delete person and organization fields
            projects:read: Read projects and its fields, tasks and project templates
            projects:full: Create, read, update and delete projects and its fields; add projects templates and project related tasks
            users:read: Read data about users (people with access to a Pipedrive account), their permissions, roles and followers
            recents:read: Read all recent changes occurred in an account. Includes data about activities, activity types, deals, files, filters, notes, persons, organizations, pipelines, stages, products and users
            search:read: Search across the account for deals, persons, organizations, files and products, and see details about the returned results
            admin: Allows to do many things that an administrator can do in a Pipedrive company account - create, read, update and delete pipelines and its stages; deal, person and organization fields; activity types; users and permissions, etc. It also allows the app to create webhooks and fetch and delete webhooks that are created by the app
            leads:read: Read data about leads and lead labels
            leads:full: Create, read, update and delete leads and lead labels
            phone-integration: Enables advanced call integration features like logging call duration and other metadata, and play call recordings inside Pipedrive
            goals:read: Read data on all goals
            goals:full: Create, read, update and delete goals
            video-calls: Allows application to register as a video call integration provider and create conference links
            messengers-integration: Allows application to register as a messengers integration provider and allows them to deliver incoming messages and their statuses
