openapi: 3.0.1
info:
  title: Pipedrive API v1 Activities Files API
  version: 1.0.0
  description: 'Activities are appointments/tasks/events on a calendar that can be associated with a deal, a lead, a person and an organization. Activities can be of different type (such as call, meeting, lunch or a custom type - see ActivityTypes object) and can be assigned to a particular user. Note that activities can also be created without a specific date/time.

    '
servers:
- url: https://api.pipedrive.com/v1
tags:
- name: Files
  description: 'Files are documents of any kind (images, spreadsheets, text files, etc.) that are uploaded to Pipedrive, and usually associated with a particular deal, person, organization, product, note or activity. Remote files can only be associated with a particular deal, person or organization. Note that the API currently does not support downloading files although it lets you retrieve a file’s meta-info along with a URL which can be used to download the file by using a standard HTTP GET request.

    '
paths:
  /files:
    get:
      summary: Get all files
      description: Returns data about all files.
      x-token-cost: 20
      operationId: getFiles
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:read
        - deals:full
        - activities:read
        - activities:full
        - contacts:read
        - contacts:full
      parameters:
      - in: query
        name: start
        description: Pagination start
        schema:
          type: integer
          default: 0
      - in: query
        name: limit
        description: Items shown per page. Please note that a maximum value of 100 is allowed.
        schema:
          type: integer
          maximum: 100
      - in: query
        name: sort
        schema:
          type: string
        description: 'Supported fields: `id`, `update_time`'
      responses:
        '200':
          description: Get data about all files uploaded to Pipedrive
          content:
            application/json:
              schema:
                title: GetFilesResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: array
                    items:
                      type: object
                      description: The file data
                      properties:
                        id:
                          type: integer
                          description: The ID of the file
                        user_id:
                          type: integer
                          description: The ID of the user to associate the file with
                        deal_id:
                          type: integer
                          description: The ID of the deal to associate the file with
                        person_id:
                          type: integer
                          description: The ID of the person to associate the file with
                        org_id:
                          type: integer
                          description: The ID of the organization to associate the file with
                        product_id:
                          type: integer
                          description: The ID of the product to associate the file with
                        activity_id:
                          type: integer
                          description: The ID of the activity to associate the file with
                        lead_id:
                          type: string
                          description: The ID of the lead to associate the file with
                          format: uuid
                        add_time:
                          type: string
                          description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                        update_time:
                          type: string
                          description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                        file_name:
                          type: string
                          description: The original name of the file
                        file_size:
                          type: integer
                          description: The size of the file
                        active_flag:
                          type: boolean
                          description: Whether the user is active or not. false = Not activated, true = Activated
                        inline_flag:
                          type: boolean
                          description: Whether the file was uploaded as inline or not
                        remote_location:
                          type: string
                          description: The location type to send the file to. Only googledrive is supported at the moment.
                        remote_id:
                          type: string
                          description: The ID of the remote item
                        cid:
                          type: string
                          description: The ID of the inline attachment
                        s3_bucket:
                          type: string
                          description: The location of the cloud storage
                        mail_message_id:
                          type: string
                          description: The ID of the mail message to associate the file with
                        mail_template_id:
                          type: string
                          description: The ID of the mail template to associate the file with
                        deal_name:
                          type: string
                          description: The name of the deal associated with the file
                        person_name:
                          type: string
                          description: The name of the person associated with the file
                        org_name:
                          type: string
                          description: The name of the organization associated with the file
                        product_name:
                          type: string
                          description: The name of the product associated with the file
                        lead_name:
                          type: string
                          description: The name of the lead associated with the file
                        url:
                          type: string
                          description: The URL of the download file
                        name:
                          type: string
                          description: The visible name of the file
                        description:
                          type: string
                          description: The description of the file
                    description: The array of all uploaded files
                  additional_data:
                    type: object
                    properties:
                      pagination:
                        title: paginationDetails
                        description: Pagination details of the list
                        type: object
                        allOf:
                        - description: The additional data of the list
                          type: object
                          properties:
                            start:
                              type: integer
                              description: Pagination start
                            limit:
                              type: integer
                              description: Items shown per page
                            more_items_in_collection:
                              type: boolean
                              description: If there are more list items in the collection than displayed or not
                        - type: object
                          properties:
                            next_start:
                              type: integer
                              description: Next pagination start
              example:
                success: true
                data:
                - id: 123
                  user_id: 456
                  deal_id: 1
                  person_id: 789
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-20 14:36:35'
                  update_time: '2020-02-20 14:57:33'
                  file_name: IMG_8189_52233498214699de9579e7b304a81b157b2eb2137e8062.jpg
                  file_type: img
                  file_size: 7801780
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1mT6jshiv6537IirwOExXJuG1jdR4F0FQ
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: ''
                  person_name: Person
                  lead_name: Test lead name
                  org_name: ''
                  product_name: ''
                  url: https://2a7f.pipedrive.com/v1/files/123/download
                  name: test file name
                  description: test file description
                - id: 123321
                  user_id: 456
                  deal_id: 1
                  person_id: 789987
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-20 14:36:35'
                  update_time: '2020-02-20 14:57:33'
                  file_name: IMG_8189_52233498214699de9579e7b304a81b157b2eb2137e8062.jpg
                  file_type: img
                  file_size: 7801780
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1mT6jshiv6537IirwOExXJuG1jdR4F0FQ
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: ''
                  person_name: Person
                  org_name: ''
                  product_name: ''
                  lead_name: Test lead name
                  url: https://2a7f.pipedrive.com/v1/files/123321/download
                  name: second test file name
                  description: second test file description
                additional_data:
                  pagination:
                    start: 0
                    limit: 100
                    more_items_in_collection: true
                    next_start: 100
    post:
      summary: Add file
      description: Lets you upload a file and associate it with a deal, person, organization, activity, product or lead. For more information, see the tutorial for <a href="https://pipedrive.readme.io/docs/adding-a-file" target="_blank" rel="noopener noreferrer">adding a file</a>.
      x-token-cost: 10
      operationId: addFile
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:full
        - activities:full
        - contacts:full
      requestBody:
        content:
          multipart/form-data:
            schema:
              title: addFileRequest
              type: object
              required:
              - file
              properties:
                file:
                  type: string
                  format: binary
                  description: A single file, supplied in the multipart/form-data encoding and contained within the given boundaries
                deal_id:
                  type: integer
                  description: The ID of the deal to associate file(s) with
                person_id:
                  type: integer
                  description: The ID of the person to associate file(s) with
                org_id:
                  type: integer
                  description: The ID of the organization to associate file(s) with
                product_id:
                  type: integer
                  description: The ID of the product to associate file(s) with
                activity_id:
                  type: integer
                  description: The ID of the activity to associate file(s) with
                lead_id:
                  type: string
                  format: uuid
                  description: The ID of the lead to associate file(s) with
      responses:
        '200':
          description: Add a file from computer or Google Drive and associate it with deal, person, organization, activity or product
          content:
            application/json:
              schema:
                title: AddFileResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    description: The file data
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
                      user_id:
                        type: integer
                        description: The ID of the user to associate the file with
                      deal_id:
                        type: integer
                        description: The ID of the deal to associate the file with
                      person_id:
                        type: integer
                        description: The ID of the person to associate the file with
                      org_id:
                        type: integer
                        description: The ID of the organization to associate the file with
                      product_id:
                        type: integer
                        description: The ID of the product to associate the file with
                      activity_id:
                        type: integer
                        description: The ID of the activity to associate the file with
                      lead_id:
                        type: string
                        description: The ID of the lead to associate the file with
                        format: uuid
                      add_time:
                        type: string
                        description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                      update_time:
                        type: string
                        description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                      file_name:
                        type: string
                        description: The original name of the file
                      file_size:
                        type: integer
                        description: The size of the file
                      active_flag:
                        type: boolean
                        description: Whether the user is active or not. false = Not activated, true = Activated
                      inline_flag:
                        type: boolean
                        description: Whether the file was uploaded as inline or not
                      remote_location:
                        type: string
                        description: The location type to send the file to. Only googledrive is supported at the moment.
                      remote_id:
                        type: string
                        description: The ID of the remote item
                      cid:
                        type: string
                        description: The ID of the inline attachment
                      s3_bucket:
                        type: string
                        description: The location of the cloud storage
                      mail_message_id:
                        type: string
                        description: The ID of the mail message to associate the file with
                      mail_template_id:
                        type: string
                        description: The ID of the mail template to associate the file with
                      deal_name:
                        type: string
                        description: The name of the deal associated with the file
                      person_name:
                        type: string
                        description: The name of the person associated with the file
                      org_name:
                        type: string
                        description: The name of the organization associated with the file
                      product_name:
                        type: string
                        description: The name of the product associated with the file
                      lead_name:
                        type: string
                        description: The name of the lead associated with the file
                      url:
                        type: string
                        description: The URL of the download file
                      name:
                        type: string
                        description: The visible name of the file
                      description:
                        type: string
                        description: The description of the file
              example:
                success: true
                data:
                  id: 123
                  user_id: 456
                  deal_id: 1
                  person_id: 789
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-20 14:36:35'
                  update_time: '2020-02-20 14:36:31'
                  file_name: IMG_8189_52233498214699de9579e7b304a81b157b2eb2137e8062.jpg
                  file_type: img
                  file_size: 7801780
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1mT6jshiv6537IirwOExXJuG1jdR4F0FQ
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: ''
                  person_name: Person
                  org_name: ''
                  product_name: ''
                  lead_name: Test lead name
                  url: https://2a7f.pipedrive.com/v1/files/123/download
                  name: IMG_8189.jpg
                  description: ''
  /files/remote:
    post:
      summary: Create a remote file and link it to an item
      description: Creates a new empty file in the remote location (`googledrive`) that will be linked to the item you supply. For more information, see the tutorial for <a href="https://pipedrive.readme.io/docs/adding-a-remote-file" target="_blank" rel="noopener noreferrer">adding a remote file</a>.
      x-token-cost: 10
      operationId: addFileAndLinkIt
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:full
        - activities:full
        - contacts:full
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              title: addFileAndLinkItRequest
              type: object
              required:
              - file_type
              - title
              - item_type
              - item_id
              - remote_location
              properties:
                file_type:
                  type: string
                  enum:
                  - gdoc
                  - gslides
                  - gsheet
                  - gform
                  - gdraw
                  description: The file type
                title:
                  type: string
                  description: The title of the file
                item_type:
                  type: string
                  enum:
                  - deal
                  - organization
                  - person
                  description: The item type
                item_id:
                  type: integer
                  description: The ID of the item to associate the file with
                remote_location:
                  type: string
                  enum:
                  - googledrive
                  description: The location type to send the file to. Only `googledrive` is supported at the moment.
      responses:
        '200':
          description: Creates a new empty file in the remote location (googledrive) that will be linked to the item you supply - deal, person or organization
          content:
            application/json:
              schema:
                title: AddRemoteFileAndLinkItToItemResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    description: The file data
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
                      user_id:
                        type: integer
                        description: The ID of the user to associate the file with
                      deal_id:
                        type: integer
                        description: The ID of the deal to associate the file with
                      person_id:
                        type: integer
                        description: The ID of the person to associate the file with
                      org_id:
                        type: integer
                        description: The ID of the organization to associate the file with
                      product_id:
                        type: integer
                        description: The ID of the product to associate the file with
                      activity_id:
                        type: integer
                        description: The ID of the activity to associate the file with
                      lead_id:
                        type: string
                        description: The ID of the lead to associate the file with
                        format: uuid
                      add_time:
                        type: string
                        description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                      update_time:
                        type: string
                        description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                      file_name:
                        type: string
                        description: The original name of the file
                      file_size:
                        type: integer
                        description: The size of the file
                      active_flag:
                        type: boolean
                        description: Whether the user is active or not. false = Not activated, true = Activated
                      inline_flag:
                        type: boolean
                        description: Whether the file was uploaded as inline or not
                      remote_location:
                        type: string
                        description: The location type to send the file to. Only googledrive is supported at the moment.
                      remote_id:
                        type: string
                        description: The ID of the remote item
                      cid:
                        type: string
                        description: The ID of the inline attachment
                      s3_bucket:
                        type: string
                        description: The location of the cloud storage
                      mail_message_id:
                        type: string
                        description: The ID of the mail message to associate the file with
                      mail_template_id:
                        type: string
                        description: The ID of the mail template to associate the file with
                      deal_name:
                        type: string
                        description: The name of the deal associated with the file
                      person_name:
                        type: string
                        description: The name of the person associated with the file
                      org_name:
                        type: string
                        description: The name of the organization associated with the file
                      product_name:
                        type: string
                        description: The name of the product associated with the file
                      lead_name:
                        type: string
                        description: The name of the lead associated with the file
                      url:
                        type: string
                        description: The URL of the download file
                      name:
                        type: string
                        description: The visible name of the file
                      description:
                        type: string
                        description: The description of the file
              example:
                success: true
                data:
                  id: 7195
                  user_id: 456
                  deal_id: 36
                  person_id: 1
                  org_id: 15
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-21 11:52:28'
                  update_time: '2020-02-21 11:52:24'
                  file_name: ''
                  file_type: gdoc
                  file_size: 0
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1gzyh6ExBxIb4RBZbAZxsrrBp45yuXhZWq3Zash5b75c
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: test deal
                  person_name: ''
                  org_name: test org
                  product_name: ''
                  lead_name: Test lead name 1
                  url: https://app.pipedrive.com/api/v1/files/7195/download
                  name: Test title for remote file
                  description: ''
  /files/remoteLink:
    post:
      summary: Link a remote file to an item
      description: Links an existing remote file (`googledrive`) to the item you supply. For more information, see the tutorial for <a href="https://pipedrive.readme.io/docs/adding-a-remote-file" target="_blank" rel="noopener noreferrer">adding a remote file</a>.
      x-token-cost: 10
      operationId: linkFileToItem
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:full
        - activities:full
        - contacts:full
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              title: linkFileToItemRequest
              type: object
              required:
              - item_type
              - item_id
              - remote_id
              - remote_location
              properties:
                item_type:
                  type: string
                  enum:
                  - deal
                  - organization
                  - person
                  description: The item type
                item_id:
                  type: integer
                  description: The ID of the item to associate the file with
                remote_id:
                  type: string
                  description: The remote item ID
                remote_location:
                  type: string
                  enum:
                  - googledrive
                  description: The location type to send the file to. Only `googledrive` is supported at the moment.
      responses:
        '200':
          description: Links an existing remote file (googledrive) to the item you supply - deal, person, organization
          content:
            application/json:
              schema:
                title: GetLinkRemoteFileToItemResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    description: The file data
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
                      user_id:
                        type: integer
                        description: The ID of the user to associate the file with
                      deal_id:
                        type: integer
                        description: The ID of the deal to associate the file with
                      person_id:
                        type: integer
                        description: The ID of the person to associate the file with
                      org_id:
                        type: integer
                        description: The ID of the organization to associate the file with
                      product_id:
                        type: integer
                        description: The ID of the product to associate the file with
                      activity_id:
                        type: integer
                        description: The ID of the activity to associate the file with
                      lead_id:
                        type: string
                        description: The ID of the lead to associate the file with
                        format: uuid
                      add_time:
                        type: string
                        description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                      update_time:
                        type: string
                        description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                      file_name:
                        type: string
                        description: The original name of the file
                      file_size:
                        type: integer
                        description: The size of the file
                      active_flag:
                        type: boolean
                        description: Whether the user is active or not. false = Not activated, true = Activated
                      inline_flag:
                        type: boolean
                        description: Whether the file was uploaded as inline or not
                      remote_location:
                        type: string
                        description: The location type to send the file to. Only googledrive is supported at the moment.
                      remote_id:
                        type: string
                        description: The ID of the remote item
                      cid:
                        type: string
                        description: The ID of the inline attachment
                      s3_bucket:
                        type: string
                        description: The location of the cloud storage
                      mail_message_id:
                        type: string
                        description: The ID of the mail message to associate the file with
                      mail_template_id:
                        type: string
                        description: The ID of the mail template to associate the file with
                      deal_name:
                        type: string
                        description: The name of the deal associated with the file
                      person_name:
                        type: string
                        description: The name of the person associated with the file
                      org_name:
                        type: string
                        description: The name of the organization associated with the file
                      product_name:
                        type: string
                        description: The name of the product associated with the file
                      lead_name:
                        type: string
                        description: The name of the lead associated with the file
                      url:
                        type: string
                        description: The URL of the download file
                      name:
                        type: string
                        description: The visible name of the file
                      description:
                        type: string
                        description: The description of the file
              example:
                success: true
                data:
                  id: 7196
                  user_id: 456
                  deal_id: 35
                  person_id: 1
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-21 12:02:37'
                  update_time: '2020-02-21 12:02:37'
                  file_name: Test title to remote file
                  file_type: gdoc
                  file_size: 0
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1gzyh6ExBxIb4RBZbAZxsrrBp45yuXhZWq3Zash5b75c
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: Test deal name
                  person_name: Test person name
                  org_name: ''
                  product_name: ''
                  lead_name: Test lead name
                  url: https://app.pipedrive.com/api/v1/files/7196/download
                  name: Test title for remote file
                  description: ''
  /files/{id}:
    delete:
      summary: Delete a file
      description: Marks a file as deleted. After 30 days, the file will be permanently deleted.
      x-token-cost: 6
      operationId: deleteFile
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:full
        - activities:full
        - contacts:full
      parameters:
      - in: path
        name: id
        description: The ID of the file
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Delete a file from Pipedrive
          content:
            application/json:
              schema:
                title: DeleteFileResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
              example:
                success: true
                data:
                  id: 123
    get:
      summary: Get one file
      description: Returns data about a specific file.
      x-token-cost: 2
      operationId: getFile
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:read
        - deals:full
        - activities:read
        - activities:full
        - contacts:read
        - contacts:full
      parameters:
      - in: path
        name: id
        description: The ID of the file
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Get data about one specific file uploaded to Pipedrive
          content:
            application/json:
              schema:
                title: GetFileResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    description: The file data
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
                      user_id:
                        type: integer
                        description: The ID of the user to associate the file with
                      deal_id:
                        type: integer
                        description: The ID of the deal to associate the file with
                      person_id:
                        type: integer
                        description: The ID of the person to associate the file with
                      org_id:
                        type: integer
                        description: The ID of the organization to associate the file with
                      product_id:
                        type: integer
                        description: The ID of the product to associate the file with
                      activity_id:
                        type: integer
                        description: The ID of the activity to associate the file with
                      lead_id:
                        type: string
                        description: The ID of the lead to associate the file with
                        format: uuid
                      add_time:
                        type: string
                        description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                      update_time:
                        type: string
                        description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                      file_name:
                        type: string
                        description: The original name of the file
                      file_size:
                        type: integer
                        description: The size of the file
                      active_flag:
                        type: boolean
                        description: Whether the user is active or not. false = Not activated, true = Activated
                      inline_flag:
                        type: boolean
                        description: Whether the file was uploaded as inline or not
                      remote_location:
                        type: string
                        description: The location type to send the file to. Only googledrive is supported at the moment.
                      remote_id:
                        type: string
                        description: The ID of the remote item
                      cid:
                        type: string
                        description: The ID of the inline attachment
                      s3_bucket:
                        type: string
                        description: The location of the cloud storage
                      mail_message_id:
                        type: string
                        description: The ID of the mail message to associate the file with
                      mail_template_id:
                        type: string
                        description: The ID of the mail template to associate the file with
                      deal_name:
                        type: string
                        description: The name of the deal associated with the file
                      person_name:
                        type: string
                        description: The name of the person associated with the file
                      org_name:
                        type: string
                        description: The name of the organization associated with the file
                      product_name:
                        type: string
                        description: The name of the product associated with the file
                      lead_name:
                        type: string
                        description: The name of the lead associated with the file
                      url:
                        type: string
                        description: The URL of the download file
                      name:
                        type: string
                        description: The visible name of the file
                      description:
                        type: string
                        description: The description of the file
              example:
                success: true
                data:
                  id: 123
                  user_id: 456
                  deal_id: 1
                  person_id: 789
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-20 14:36:35'
                  update_time: '2020-02-20 14:57:33'
                  file_name: IMG_8189_52233498214699de9579e7b304a81b157b2eb2137e8062.jpg
                  file_type: img
                  file_size: 7801780
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1mT6jshiv6537IirwOExXJuG1jdR4F0FQ
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: ''
                  person_name: Person
                  org_name: ''
                  product_name: ''
                  lead_name: Test lead name
                  url: https://2a7f.pipedrive.com/v1/files/123/download
                  name: test file name
                  description: test file description
    put:
      summary: Update file details
      description: Updates the properties of a file.
      x-token-cost: 10
      operationId: updateFile
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:full
        - activities:full
        - contacts:full
      parameters:
      - in: path
        name: id
        description: The ID of the file
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              title: updateFileRequest
              type: object
              properties:
                name:
                  type: string
                  description: The visible name of the file
                description:
                  type: string
                  description: The description of the file
      responses:
        '200':
          description: Update file name and description
          content:
            application/json:
              schema:
                title: UpdateFileResponse
                type: object
                properties:
                  success:
                    type: boolean
                    description: If the request was successful or not
                  data:
                    type: object
                    description: The file data
                    properties:
                      id:
                        type: integer
                        description: The ID of the file
                      user_id:
                        type: integer
                        description: The ID of the user to associate the file with
                      deal_id:
                        type: integer
                        description: The ID of the deal to associate the file with
                      person_id:
                        type: integer
                        description: The ID of the person to associate the file with
                      org_id:
                        type: integer
                        description: The ID of the organization to associate the file with
                      product_id:
                        type: integer
                        description: The ID of the product to associate the file with
                      activity_id:
                        type: integer
                        description: The ID of the activity to associate the file with
                      lead_id:
                        type: string
                        description: The ID of the lead to associate the file with
                        format: uuid
                      add_time:
                        type: string
                        description: 'The date and time when the file was added/created. Format: YYYY-MM-DD HH:MM:SS'
                      update_time:
                        type: string
                        description: 'The last updated date and time of the file. Format: YYYY-MM-DD HH:MM:SS'
                      file_name:
                        type: string
                        description: The original name of the file
                      file_size:
                        type: integer
                        description: The size of the file
                      active_flag:
                        type: boolean
                        description: Whether the user is active or not. false = Not activated, true = Activated
                      inline_flag:
                        type: boolean
                        description: Whether the file was uploaded as inline or not
                      remote_location:
                        type: string
                        description: The location type to send the file to. Only googledrive is supported at the moment.
                      remote_id:
                        type: string
                        description: The ID of the remote item
                      cid:
                        type: string
                        description: The ID of the inline attachment
                      s3_bucket:
                        type: string
                        description: The location of the cloud storage
                      mail_message_id:
                        type: string
                        description: The ID of the mail message to associate the file with
                      mail_template_id:
                        type: string
                        description: The ID of the mail template to associate the file with
                      deal_name:
                        type: string
                        description: The name of the deal associated with the file
                      person_name:
                        type: string
                        description: The name of the person associated with the file
                      org_name:
                        type: string
                        description: The name of the organization associated with the file
                      product_name:
                        type: string
                        description: The name of the product associated with the file
                      lead_name:
                        type: string
                        description: The name of the lead associated with the file
                      url:
                        type: string
                        description: The URL of the download file
                      name:
                        type: string
                        description: The visible name of the file
                      description:
                        type: string
                        description: The description of the file
              example:
                success: true
                data:
                  id: 123
                  user_id: 456
                  deal_id: 1
                  person_id: 789
                  org_id: 1
                  product_id: 1
                  activity_id: 1
                  lead_id: adf21080-0e10-11eb-879b-05d71fb426ec
                  log_id: null
                  add_time: '2020-02-20 14:36:35'
                  update_time: '2020-02-20 14:57:33'
                  file_name: IMG_8189_52233498214699de9579e7b304a81b157b2eb2137e8062.jpg
                  file_type: img
                  file_size: 7801780
                  active_flag: true
                  inline_flag: false
                  remote_location: googledocs
                  remote_id: 1mT6jshiv6537IirwOExXJuG1jdR4F0FQ
                  cid: ''
                  s3_bucket: ''
                  mail_message_id: ''
                  mail_template_id: ''
                  deal_name: ''
                  person_name: Person
                  org_name: ''
                  product_name: ''
                  lead_name: Test lead name
                  url: https://2a7f.pipedrive.com/v1/files/123/download
                  name: test file name
                  description: test file description
  /files/{id}/download:
    get:
      summary: Download one file
      description: Initializes a file download.
      x-token-cost: 20
      x-binary-response: true
      operationId: downloadFile
      tags:
      - Files
      security:
      - api_key: []
      - oauth2:
        - deals:read
        - deals:full
        - activities:read
        - activities:full
        - contacts:read
        - contacts:full
      parameters:
      - in: path
        name: id
        description: The ID of the file
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/octet-stream:
              schema:
                title: GetDownloadFileResponse
                type: string
                format: byte
components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic
      description: Base 64 encoded string containing the `client_id` and `client_secret` values. The header value should be `Basic <base64(client_id:client_secret)>`.
    api_key:
      type: apiKey
      name: x-api-token
      in: header
    oauth2:
      type: oauth2
      description: For more information, see https://pipedrive.readme.io/docs/marketplace-oauth-authorization
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.pipedrive.com/oauth/authorize
          tokenUrl: https://oauth.pipedrive.com/oauth/token
          refreshUrl: https://oauth.pipedrive.com/oauth/token
          scopes:
            base: Read settings of the authorized user and currencies in an account
            deals:read: Read most of the data about deals and related entities - deal fields, products, followers, participants; all notes, files, filters, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            deals:full: Create, read, update and delete deals, its participants and followers; all files, notes, and filters. It also includes read access to deal fields, pipelines, stages, and statistics. Does not include access to activities (except the last and next activity related to a deal)
            mail:read: Read mail threads and messages
            mail:full: Read, update and delete mail threads. Also grants read access to mail messages
            activities:read: Read activities, its fields and types; all files and filters
            activities:full: Create, read, update and delete activities and all files and filters. Also includes read access to activity fields and types
            contacts:read: Read the data about persons and organizations, their related fields and followers; also all notes, files, filters
            contacts:full: Create, read, update and delete persons and organizations and their followers; all notes, files, filters. Also grants read access to contacts-related fields
            products:read: Read products, its fields, files, followers and products connected to a deal
            products:full: Create, read, update and delete products and its fields; add products to deals
            deal-fields:full: Create, read, update and delete deal fields
            product-fields:full: Create, read, update and delete product fields
            contact-fields:full: Create, read, update and delete person and organization fields
            projects:read: Read projects and its fields, tasks and project templates
            projects:full: Create, read, update and delete projects and its fields; add projects templates and project related tasks
            users:read: Read data about users (people with access to a Pipedrive account), their permissions, roles and followers
            recents:read: Read all recent changes occurred in an account. Includes data about activities, activity types, deals, files, filters, notes, persons, organizations, pipelines, stages, products and users
            search:read: Search across the account for deals, persons, organizations, files and products, and see details about the returned results
            admin: Allows to do many things that an administrator can do in a Pipedrive company account - create, read, update and delete pipelines and its stages; deal, person and organization fields; activity types; users and permissions, etc. It also allows the app to create webhooks and fetch and delete webhooks that are created by the app
            leads:read: Read data about leads and lead labels
            leads:full: Create, read, update and delete leads and lead labels
            phone-integration: Enables advanced call integration features like logging call duration and other metadata, and play call recordings inside Pipedrive
            goals:read: Read data on all goals
            goals:full: Create, read, update and delete goals
            video-calls: Allows application to register as a video call integration provider and create conference links
            messengers-integration: Allows application to register as a messengers integration provider and allows them to deliver incoming messages and their statuses
